### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by ouija** [dmhacker/dmhacker-youtube#10]
Getting an error when using this:

```
2018-02-09T07:46:20.996613+00:00 app[web.1]: Query result: Metallica - Enter Sandman [Official Music Video]
2018-02-09T07:46:21.695946+00:00 app[web.1]: events.js:154
2018-02-09T07:46:21.696003+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2018-02-09T07:46:21.696019+00:00 app[web.1]:       ^
2018-02-09T07:46:21.696035+00:00 app[web.1]: 
2018-02-09T07:46:21.696052+00:00 app[web.1]: Error: Could not extract signature deciphering actions
2018-02-09T07:46:21.696054+00:00 app[web.1]:     at /app/node_modules/ytdl-core/lib/sig.js:48:11
2018-02-09T07:46:21.696056+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/ytdl-core/lib/request.js:43:9)
2018-02-09T07:46:21.696058+00:00 app[web.1]:     at emitNone (events.js:85:20)
2018-02-09T07:46:21.696059+00:00 app[web.1]:     at IncomingMessage.emit (events.js:179:7)
2018-02-09T07:46:21.696061+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:913:12)
2018-02-09T07:46:21.696063+00:00 app[web.1]:     at _combinedTickCallback (node.js:383:13)
2018-02-09T07:46:21.696078+00:00 app[web.1]:     at process._tickCallback (node.js:407:11)
2018-02-09T07:46:21.631122+00:00 heroku[router]: at=info method=GET path="/alexa-check/CD-E-LDc384" host=xxxx.herokuapp.com request_id=447829c3-796b-4e26-b541-e7053e48b82b fwd="34.230.17.7" dyno=web.1 connect=1ms service=14ms status=200 bytes=273 protocol=https
2018-02-09T07:46:21.797499+00:00 heroku[web.1]: State changed from up to crashed
2018-02-09T07:46:21.784314+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by ouija** [comment]
Managed to resolve it by updating the "ytdl-core" package to the latest version (0.20.1) under my forked repo.  Note I updated all the outdated packages to their latest versions and it works well, no more crashing (so far)
