### ISSUE TITLE
Cannot retrieve downloaded videos and 503 service unavailable in frontend

### ISSUE THREAD

**Issue by federicoparroni** [dmhacker/dmhacker-youtube#20]
Hi! I have deployed the service into Heruko following the guide you provided. When I do any action on the frontend app I get:

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```
The strange thing is that I got the error above also using your service at [https://dmhacker-youtube.herokuapp.com](https://dmhacker-youtube.herokuapp.com).

Here is the log I collected from Heroku console:
```
2020-08-17T07:15:39.310757+00:00 app[web.1]: {
2020-08-17T07:15:39.310792+00:00 app[web.1]:   id: '4VR-6AS0-l4',
2020-08-17T07:15:39.310794+00:00 app[web.1]:   link: 'https://youtube.com/watch?v=4VR-6AS0-l4',
2020-08-17T07:15:39.310795+00:00 app[web.1]:   title: 'Ludovico Einaudi - Nuvole Bianche'
2020-08-17T07:15:39.310795+00:00 app[web.1]: }
2020-08-17T07:15:40.308584+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/search/nuvole%20bianche" host=aaaaaaa.herokuapp.com request_id=3ee6359c-c5bd-4188-81c0-ba0c760ca114 fwd="82.51.125.173" dyno=web.1 connect=0ms service=1783ms status=503 bytes=0 protocol=https
2020-08-17T07:15:40.303649+00:00 app[web.1]: internal/validators.js:117
2020-08-17T07:15:40.303682+00:00 app[web.1]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
2020-08-17T07:15:40.303683+00:00 app[web.1]:     ^
2020-08-17T07:15:40.303683+00:00 app[web.1]: 
2020-08-17T07:15:40.303694+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
2020-08-17T07:15:40.303694+00:00 app[web.1]:     at validateString (internal/validators.js:117:11)
2020-08-17T07:15:40.303695+00:00 app[web.1]:     at Url.parse (url.js:159:3)
2020-08-17T07:15:40.303695+00:00 app[web.1]:     at Object.urlParse [as parse] (url.js:154:13)
2020-08-17T07:15:40.303697+00:00 app[web.1]:     at doDownload (/app/node_modules/miniget/dist/index.js:90:28)
2020-08-17T07:15:40.303697+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
2020-08-17T07:15:40.303697+00:00 app[web.1]:   code: 'ERR_INVALID_ARG_TYPE'
2020-08-17T07:15:40.303698+00:00 app[web.1]: }
2020-08-17T07:15:40.347133+00:00 heroku[web.1]: Process exited with status 1
2020-08-17T07:15:40.381539+00:00 heroku[web.1]: State changed from up to crashed
```

If instead I try with your api, this is what happens:
```bash
curl https://dmhacker-youtube.herokuapp.com/alexa/v3/search/bnV2b2xlIGJpYW5jaGU=?language=it
{"state":"success","message":"Found video result","video":{"id":"4VR-6AS0-l4","title":"Ludovico Einaudi - Nuvole Bianche","link":"https://www.youtube.com/watch?v=4VR-6AS0-l4"}}

curl https://dmhacker-youtube.herokuapp.com/alexa/v3/download/4VR-6AS0-l4
{"state":"success","message":"Beginning download process.","link":"/site/4VR-6AS0-l4.m4a"}

curl https://dmhacker-youtube.herokuapp.com/alexa/v3/cache/4VR-6AS0-l4
{"state":"success","message":"Not in cache"}
```

Am I doing something wrong?

**Comment by federicoparroni** [comment]
I solved by updating `ytdl-core` from `2.1.1` to `3.2.1`. It is sufficient to do the following:
```bash
npm uninstall ytdl-core && npm install ytdl-core
```
