### ISSUE TITLE
Lamda function failed

### ISSUE THREAD

**Issue by loctruong96** [dmhacker/dmhacker-youtube#4]
The lamda function failed with this error. Do you have any suggestions as of why?
Thank you so much!
```
2017-08-10T09:13:51.892Z	39847bd5-7dac-11e7-bf61-c376ad7ff20a	SyntaxError: Unexpected token C in JSON at position 0
at Object.parse (native)
at Request._callback (/var/task/index.js:78:29)
at Request.self.callback (/var/task/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/var/task/node_modules/request/request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1091:12)
at IncomingMessage.g (events.js:292:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by dmhacker** [comment]
~~I'm going to close this issue here and move it to the [skill repository](https://github.com/dmhacker/alexa-youtube-skill).~~ The Heroku server doesn't require a Lambda machine. 

Edit: I see you already opened this issue over there.
