### ISSUE TITLE
Starting process with command `node app.js` crashed

### ISSUE THREAD

**Issue by loctruong96** [dmhacker/dmhacker-youtube#5]
Hello, I follow your new instruction, it deployed successfully but the log say app crashed after starting:
```
2017-08-12T22:36:56.160020+00:00 heroku[web.1]: State changed from crashed to starting
2017-08-12T22:36:59.478981+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-08-12T22:37:01.374424+00:00 app[web.1]: bash: node: command not found
2017-08-12T22:37:01.423978+00:00 heroku[web.1]: Process exited with status 127
2017-08-12T22:37:01.437545+00:00 heroku[web.1]: State changed from starting to crashed

```
Do I have to do something to specify this is a node js app?

Thank you,

**Comment by loctruong96** [comment]
So I thought tried to fix this by changing the version in the package.json engine to node version 6.11.2 , but that didn't do anything :(

**Comment by dmhacker** [comment]
What buildpacks do you have selected?

**Comment by loctruong96** [comment]
this one : `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`

**Comment by dmhacker** [comment]
Do you have the `heroku/nodejs` buildpack installed too? If not, add that.

**Comment by loctruong96** [comment]
Which one should i use, there are so many version O_O

**Comment by loctruong96** [comment]
i used the latest one and came out with a bunch of errors

**Comment by dmhacker** [comment]
Try using the one with version 5.9.1 or a version similar to that?

**Comment by loctruong96** [comment]
Okay, so I added the node js buildpack 5.9.1 and build successful deployed, but then the exact error occurred again with newer build pack.
`2017-08-13T01:31:47.874697+00:00 app[web.1]: Error: Cannot find module 'youtube-search'
2017-08-13T01:31:47.874701+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2017-08-13T01:31:47.874699+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2017-08-13T01:31:47.874698+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2017-08-13T01:31:47.874702+00:00 app[web.1]:     at Module.load (module.js:357:32)
2017-08-13T01:31:47.874702+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2017-08-13T01:31:47.874703+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2017-08-13T01:31:47.874704+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)`

**Comment by loctruong96** [comment]
There is a bug in your package.json where the dependencies have a typo and a missing package. The original: 
```
"dependencies": {
        "ejs": "2.4.1",
        "express": "4.13.3",
        "ytdl-core": "0.9.1",
        "fluent-ffmpeg": "^2.1.0"	
    }
```
I fix it to, everything run great now. Thank you for your support!
```
"dependencies": {
        "ejs": "2.4.1",
        "express": "4.13.3",
        "ytdl-core": "0.9.1",
        "fluent-ffmpeg": "2.1.0",
	"youtube-search": "1.0.10"
    }
```
